version: '3.9'
services:
  tomp-gateway:
    build: .
    environment:
      - NODE_ENV=local
      - TOMP_API_VERSION=1.0.0
      - TOMP_ACCEPT_LANGUAGE=nl
      - TOMP_MAAS_ID=d52bfad0-ee4b-4f72-9f38-efce115ffb49
      - TOMP_TRANSPORT_OPERATOR_BASE_URL=http://3.123.228.24:8083 
      - API=TOMP
    ports:
      - '2900:2900'
